task = "data/training_models/test"
[logger]
filename = "train"
name = "TRAIN"

[model]
"@name" = "dqn_v2"
n_emb = 16
n_feat = 32
[model.params]
alpha = 0.0
beta = 0.5
dqn = true
[model.reaction_model]
"@name" = "painn" 
model_path = "models/reaction_model.pth.tar" # Assuming reaction model is in models directory

[train]
device = "cuda"
horizon = 50
lr = 1e-5
mode = "dqn"
n_episodes = 10
n_poscars = [1]
poscar_dir = ["data"] # Change this to the directory where your POSCAR files are stored.
temperature = [300, 500, 700, 900]
train_all = true
memory_batch_size = 64 # Num of transitions per batch

[train.update_params]
batch_size = 8
gamma = 0.9
num_epoch = 5

[train.calc_info]
cutoff = 4.0
device = "cuda"
max_iter = 100
platform = "mace"
relax_accuracy = 0.05
relax_log = "relax.log"

[misc]
prioritized_memory = true #Prioritized Experience Replay. If false, uses random sampling